// user action types

export const AUTHUSER_POST = "AUTHUSER_POST"
export const AUTHUSER_POST_SUCCESS = "AUTHUSER_POST_SUCCESS"

export const POST_LIKE = "POST_LIKE"
export const POST_LIKE_SUCCESS = "POST_LIKE_SUCCESS"

export const USERS_POST = "USERS_POST"
export const USERS_POST_SUCCESS = "USERS_POST_SUCCESS"

export default {
  AUTHUSER_POST,
  AUTHUSER_POST_SUCCESS,
  POST_LIKE,
  POST_LIKE_SUCCESS,
  USERS_POST,
  USERS_POST_SUCCESS
}
