// auth action types
export const AUTH_CHECK = "AUTH_CHECK";
export const AUTH_USER = "AUTH_USER";
export const AUTH_ECHO_SETUP = "AUTH_ECHO_SETUP";
export const USER_LOAD = "USER_LOAD";
export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS";
export const USER_LOAD_ERROR = "USER_LOAD_ERROR";
export const UPDATE_COINS = "UPDATE_COINS";
export const UPDATE_COINS_SUCCESS = "UPDATE_COINS_SUCCESS";
export const UPDATE_COINS_ERROR = "UPDATE_COINS_ERROR";
export const TRANSACTION_LOAD = "TRANSACTION_LOAD";
export const TRANSACTION_LOAD_SUCCESS = "TRANSACTION_LOAD_SUCCESS";
export const TRANSACTION_LOAD_ERROR = "TRANSACTION_LOAD_ERROR";

export default {
  AUTH_CHECK,
  AUTH_USER,
  AUTH_ECHO_SETUP,
  USER_LOAD,
  USER_LOAD_SUCCESS,
  USER_LOAD_ERROR,
  UPDATE_COINS,
  UPDATE_COINS_SUCCESS,
  UPDATE_COINS_ERROR,
  TRANSACTION_LOAD,
  TRANSACTION_LOAD_SUCCESS,
  TRANSACTION_LOAD_ERROR
};
