// auth action types
export const AUTH_CHECK = "AUTH_CHECK";
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_ERROR = "AUTH_LOGIN_ERROR";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_FORGOT_PASSWORD = "AUTH_FORGOT_PASSWORD";
export const AUTH_FORGOT_PASSWORD_ERROR = "AUTH_FORGOT_PASSWORD_ERROR";
export const AUTH_FORGOT_PASSWORD_SUCCESS = "AUTH_FORGOT_PASSWORD_SUCCESS";
export const AUTH_VERIFY_CODE = "AUTH_VERIFY_CODE";
export const AUTH_VERIFY_CODE_ERROR = "AUTH_VERIFY_CODE_ERROR";
export const AUTH_VERIFY_CODE_SUCCESS = "AUTH_VERIFY_CODE_SUCCESS";
export const AUTH_RESET_PASSWORD = "AUTH_RESET_PASSWORD";
export const AUTH_RESET_PASSWORD_ERROR = "AUTH_RESET_PASSWORD_ERROR";
export const AUTH_RESET_PASSWORD_SUCCESS = "AUTH_RESET_PASSWORD_SUCCESS";
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_ERROR = "AUTH_REGISTER_ERROR";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";
export const AUTH_REFRESH_TOKEN = "AUTH_REFRESH_TOKEN";
export const AUTH_USER = "AUTH_USER";
export const AUTH_ECHO_SETUP = "AUTH_ECHO_SETUP";
export const GET_CAR = "GET_CAR";
export const GET_CAR_SUCCESS = "GET_CAR_SUCCESS";
export const AUTH_RESEND_EMAIL = "AUTH_RESEND_EMAIL";
export const AUTH_RESEND_EMAIL_ERROR = "AUTH_RESEND_EMAIL_ERROR";
export const AUTH_RESEND_EMAIL_SUCCESS = "AUTH_RESEND_EMAIL_SUCCESS";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";
export const UPDATE_SOCIAL_MEDIA = "UPDATE_SOCIAL_MEDIA";
export const UPDATE_SOCIAL_MEDIA_SUCCESS = "UPDATE_SOCIAL_MEDIA_SUCCESS";
export const UPDATE_SOCIAL_MEDIA_ERROR = "UPDATE_SOCIAL_MEDIA_ERROR";
export const UPDATE_COINS = "UPDATE_COINS";
export const UPDATE_COINS_SUCCESS = "UPDATE_COINS_SUCCESS";
export const UPDATE_COINS_ERROR = "UPDATE_COINS_ERROR";

export default {
  AUTH_CHECK,
  AUTH_LOGIN,
  AUTH_LOGIN_ERROR,
  AUTH_LOGIN_SUCCESS,
  AUTH_REGISTER,
  AUTH_REGISTER_ERROR,
  AUTH_REGISTER_SUCCESS,
  AUTH_LOGOUT,
  AUTH_LOGOUT_SUCCESS,
  AUTH_REFRESH_TOKEN,
  AUTH_USER,
  AUTH_ECHO_SETUP,
  AUTH_FORGOT_PASSWORD,
  AUTH_FORGOT_PASSWORD_ERROR,
  AUTH_FORGOT_PASSWORD_SUCCESS,
  AUTH_VERIFY_CODE,
  AUTH_VERIFY_CODE_ERROR,
  AUTH_VERIFY_CODE_SUCCESS,
  AUTH_RESET_PASSWORD,
  AUTH_RESET_PASSWORD_ERROR,
  AUTH_RESET_PASSWORD_SUCCESS,
  GET_CAR,
  GET_CAR_SUCCESS,
  AUTH_RESEND_EMAIL,
  AUTH_RESEND_EMAIL_ERROR,
  AUTH_RESEND_EMAIL_SUCCESS,
  UPDATE_PROFILE,
  UPDATE_PROFILE_SUCCESS,
  UPDATE_PROFILE_ERROR,
  UPDATE_SOCIAL_MEDIA,
  UPDATE_SOCIAL_MEDIA_SUCCESS,
  UPDATE_SOCIAL_MEDIA_ERROR,
  UPDATE_COINS,
  UPDATE_COINS_SUCCESS,
  UPDATE_COINS_ERROR
};
