// web action types
export const DETAIL_CHANGED = "DETAIL_CHANGED"
export const PAGE_CHANGED = "PAGE_CHANGED"
export const MENU_CHANGED = "MENU_CHANGED"
export const QUICK_BAR_CHANGED = "QUICK_BAR_CHANGED"
export const MODAL_CHANGED = "MODAL_CHANGED"
export const MODAL_CLOSE = "MODAL_CLOSE"
export const ALERT_ADDED = "ALERT_ADDED"
export const ALERT_REMOVED = "ALERT_REMOVED"
export const REQUEST = "REQUEST"
export const EVENT_FIRED = "EVENT_FIRED"

export default {
  DETAIL_CHANGED,
  PAGE_CHANGED,
  QUICK_BAR_CHANGED,
  MENU_CHANGED,
  MODAL_CHANGED,
  MODAL_CLOSE,
  ALERT_ADDED,
  ALERT_REMOVED,
  REQUEST,
  EVENT_FIRED
}
