// user action types
export const USER_LOAD = "USER_LOAD";
export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS";
export const INITIAL_SEARCH_USER = "INITIAL_SEARCH_USER";
export const INITIAL_SEARCH_USER_SUCCESS = "INITIAL_SEARCH_USER_SUCCESS";
export const SEARCH_USER = "SEARCH_USER";
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS";

export default {
  USER_LOAD,
  USER_LOAD_SUCCESS,
  INITIAL_SEARCH_USER,
  INITIAL_SEARCH_USER_SUCCESS,
  SEARCH_USER,
  SEARCH_USER_SUCCESS
};
