// auth action types
export const AUTH_CHECK = "AUTH_CHECK";
export const AUTH_USER = "AUTH_USER";
export const AUTH_ECHO_SETUP = "AUTH_ECHO_SETUP";
export const USER_LOAD = "USER_LOAD";
export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS";
export const USER_LOAD_ERROR = "USER_LOAD_ERROR";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";
export const UPDATE_SOCIAL_MEDIA = "UPDATE_SOCIAL_MEDIA";
export const UPDATE_SOCIAL_MEDIA_SUCCESS = "UPDATE_SOCIAL_MEDIA_SUCCESS";
export const UPDATE_SOCIAL_MEDIA_ERROR = "UPDATE_SOCIAL_MEDIA_ERROR";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_ERROR = "UPDATE_PASSWORD_ERROR";

export default {
  AUTH_CHECK,
  AUTH_USER,
  AUTH_ECHO_SETUP,
  USER_LOAD,
  USER_LOAD_SUCCESS,
  USER_LOAD_ERROR,
  UPDATE_PROFILE,
  UPDATE_PROFILE_SUCCESS,
  UPDATE_PROFILE_ERROR,
  UPDATE_SOCIAL_MEDIA,
  UPDATE_SOCIAL_MEDIA_SUCCESS,
  UPDATE_SOCIAL_MEDIA_ERROR,
  UPDATE_PASSWORD,
  UPDATE_PASSWORD_SUCCESS,
  UPDATE_PASSWORD_ERROR
};
